### ISSUE TITLE
Compiler bitching about invalid conversion.

### ISSUE THREAD

**Issue by michpolicht** [lukedeo/cmd-parser#4]
Function eat_arguments() should accept "char \* argv[]" instead of "const char \* argv[]". This is how you pass it to main().

`void parser::eat_arguments(int argc, char *argv[])`

instead of

`void parser::eat_arguments(int argc, const char *argv[])`

**Comment by lukedeo** [comment]
@michpolicht open a PR?

**Comment by michpolicht** [comment]
You can just change it bro. Merging my code with your would make me a 
co-author ;)

Regards.

Luke de Oliveira wrote:
